### ISSUE TITLE
new connection on port: banana

### ISSUE THREAD

**Issue by CWSpear** [defunctzombie/localtunnel-server#10]
I was having issues setting it up on my server, so I started testing locally and got similar results.

I cloned `localtunnel-server` locally and ran this command:

```bash
env DEBUG="localtunnel*" bin/server --port 1234
```

Then I ran this command in another shell:

```bash
 lt --host http://localhost:1234 --port 8000 --subdomain banana
```

(I have a Laravel app running on port 8000 and `lt --port 8000` works going through `localtunnel.me`.)

The client says my url is `http://banana.localhost:1234` and if I go there (I added banana.localhost to my `hosts`), then I get the main index of what's at localtunnel.me.

The server debug output says a bunch of stuff about connection to port "banana" when I connect the client.

```
  localtunnel server listening on port: 1234 +0ms
  localtunnel-server request /banana +0ms
  localtunnel-server making new client with id banana +11ms
  localtunnel-server tcp server listening on port: 50814 +1ms
  localtunnel-server new connection on port: banana +12ms
  localtunnel-server new connection on port: banana +0ms
  localtunnel-server new connection on port: banana +1ms
  localtunnel-server new connection on port: banana +0ms
  localtunnel-server new connection on port: banana +0ms
  localtunnel-server new connection on port: banana +1ms
  localtunnel-server new connection on port: banana +0ms
  localtunnel-server new connection on port: banana +0ms
  localtunnel-server new connection on port: banana +0ms
  localtunnel-server new connection on port: banana +1ms
  localtunnel-server request / +8s
  localtunnel-server request /static/541f20/css/style.css +496ms
  localtunnel-server request /static/99735c/css/grid.css +1ms
  localtunnel-server request /static/0f1bee/css/widgets.css +1ms
  localtunnel-server request /static/21e1e0/js/index.js +1ms
  localtunnel-server request /engine.io/?EIO=2&transport=websocket&sid=6RlMHqlk_JJVrx9UAAAA +216ms
```

This is more or less what was happening on my server, too, except I was having issues with the `maybe_bounce` function. If I forced it to return `false`, then my experience on the server is the same as that.

**Comment by defunctzombie** [comment]
I think the issues here have been resolved.
