### ISSUE TITLE
Need help in configuring DNS subdomain on Amazon AWS

### ISSUE THREAD

**Issue by CSRaghunandan** [defunctzombie/localtunnel-server#117]
Hello,

I got the server hosted on a linux instance running on Amazon EC2. I have also opened all TCP inbound ports so that localtunnel can utilize them for opening TCP connections.

I have the DNS setup done so that I can access my website through my domain registered in godaddy. But, when I try to use localtunnel client with my domain running localtunnel, I can see that the client is unable to reach to the host server.

I have another nodejs server running on the EC2 instance and I'm able to access that using the same domain, so I'm not sure where the problem is. But I think its due to DNS configuration in amazon aws. In particular, I need  help in setting up the subdomain configuration as mentioned in the docs:

> You can set up DNS entries for your domain.tld and *.domain.tld (or sub.domain.tld and *.sub.domain.tld).

Could someone please help me in getting localtunnel server to work correctly.

EDIT: was able to fix the DNS config issue

Thank you.

**Comment by caprico-codes** [comment]
@CSRaghunandan Hey buddy I am facing the same problem on an aws ec2 instance. The client is unable to reach the host server. How did you solve the problem? Do you have a link that I can follow?

**Comment by CSRaghunandan** [comment]
Hey, you need to setup a DNS A record for wildcard domains.
An example here: https://www.namecheap.com/support/knowledgebase/article.aspx/597/2237/how-can-i-set-up-a-catchall-wildcard-subdomain

Hope that helps you.

**Comment by caprico-codes** [comment]
@CSRaghunandan Ya I expected this. I did use a wildcard (*) as host while creating a A record in Freenom. But they dont support wildcards for free domains. So I guess all I need to do is to find a service that does.

**Comment by CSRaghunandan** [comment]
Godaddy supports free wildcard domains, as does namecheap I think (but not too sure, you've to check)

I ran into a similar problem with amazon aws DNS, it did not support wildcard domains.

**Comment by caprico-codes** [comment]
@CSRaghunandan So the wildcard problem is solved after I shifted to Namecheap. But now when I start my localtunnel client, there is no response at all. I dont even get a url to follow.  And theres no error on the server side. Were you able to successfully deploy your own server and connect to it?

**Comment by CSRaghunandan** [comment]
I was not able to get localtunnel to work at all, I had the same issue as you.

I gave up and started using serveo instead. Maybe there are other open source alternatives which works similar to localtunnel/serveo, I need to explore a bit more.
