### ISSUE TITLE
'bin/server' Command is not Available

### ISSUE THREAD

**Issue by ssghost** [defunctzombie/localtunnel-server#138]
I successfully installed localtunnel/server on an Ubuntu 18.04 VPS through ssh.
When I typed `bin/server` to start the server, this message came out:  
`/usr/bin/env: ‘node -r esm’: No such file or directory`

How to fix it?

**Comment by gkosmas** [comment]
Same here. Spent some time trying to troubleshoot but no dice.

**Comment by krynble** [comment]
This matter has been discussed here: https://github.com/localtunnel/server/issues/90

Seems like running `node -r esm ./bin/server` instead of `npm run start` works for a few cases.

**Comment by ikbelkirasan** [comment]
Try using Node 10 instead of later versions and it should work.

**Comment by StyleT** [comment]
Fixed this issue here https://github.com/StyleT/mytunnel-server It now runs on latest Node.js LTS via `npm start`.
