### ISSUE TITLE
node -r esm: No such file or directory

### ISSUE THREAD

**Issue by Neilblaze** [defunctzombie/localtunnel-server#139]
I am getting this error while running localtunnel on `HTTP`. Can anyone tell me what can possibly fix this issue?

**Comment by DanieleSalatti** [comment]
Try removing the `#!` line from `bin/server` and running it with ` node -r esm ./bin/server`.

Let me know if it works...

**Comment by siburny** [comment]
See more info here: https://github.com/localtunnel/server/issues/90

**Comment by Neilblaze** [comment]
@DanieleSalatti Thank you very much! :smiley:
It worked!

**Comment by DanieleSalatti** [comment]
@Neilblaze glad I could help 😀

**Comment by zcmgyu** [comment]
@DanieleSalatti Thanks. It worked for me. But it just worked on node v10. Version v14 and v15 not work for me.

**Comment by DanieleSalatti** [comment]
Hey @zcmgyu 

I am not using localtunnel anymore at the moment. I can try looking into it later on if I have time.

Might be worth opening a new issue with more details on your setup for the maintainer to look into :)
