### ISSUE TITLE
Mysterious unhandled error event

### ISSUE THREAD

**Issue by rutaihwa** [defunctzombie/localtunnel-server#14]
Hello,
I got interested in trying out localtunnel but everytime i run it with my local servers i get 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connection refused: localtunnel.me:40283 (check your firewall settings)

What don't i do right?

**Comment by femto** [comment]
Error: connection refused: localtunnel.me:40504 (check your firewall settings)

Every once in a while this happens, it's weird.

**Comment by aboutaaron** [comment]
I have the same issue.

**Comment by TorinAsakura** [comment]
Me too… ![me too](http://monosnap.com/image/od65D5ySuUNy5XlxwRJG5gr4hEDqUt.png)

**Comment by cleverlight** [comment]
Me too.  I suspect this is caused by a port's lease expiring.  I don't know how localtunnel works, but I wonder if it's using something like UPnP to open a port first on local machine, then gateway/network router.  Those leases perhaps expire after a while?

**Comment by igorsantos07** [comment]
I know little about network to help debug the issue, but I do use localtunnel frequently in my company to debug mobile websites, and sooner or later that error appears and the localtunnel connection dies. I'm happy to help with testing, if needed, tho.

**Comment by jvpsousa** [comment]
I have the same issue, the tunnel works for a while , then it crashes with the same error.

**Comment by ciokan** [comment]
you're probably using nodemon or something which restarts the server causing the port to go down for a brief moment

**Comment by fidalgo** [comment]
This error is happening with me too... after a while the connection goes down. Is there anything I could do to help tracing the problem?

**Comment by ekosten** [comment]
You need to install localtunnel globally:
npm install -g localtunnel

**Comment by igorsantos07** [comment]
@ekosten I guess this is actually the default recommendation?

**Comment by renandecarlo** [comment]
This happens to me every once in a while too.

**Comment by novacp** [comment]
I am getting the same error message as described in the uploaded images. Any news on how to avoid it ?
--Regards

**Comment by ZECTBynmo** [comment]
+1

**Comment by lizdizon** [comment]
+1

**Comment by igorsantos07** [comment]
For simple uses of localtunnel (i.e. Not attached to browsersync), I've migrated to ngrok.io. Reliable and also seems more powerful (?). The install procedure is the same, `npm install -g ngrok`

**Comment by minifigmaster125** [comment]
The ngrok solution does work well, but requires a paid subscription for custom subdomains. Still curious about a solution for localtunnel.

**Comment by defunctzombie** [comment]
I haven't had time to look into it but to likely just a missing error
handler.

**Comment by jjwyse** [comment]
+1

**Comment by jon64digital** [comment]
Same here, a few times a day, sometimes after 5 minutes, sometimes after many hours. Using gulp and browsersync

**Comment by zeepeeare** [comment]
+1, frequently experiencing this issue.

**Comment by MaxPleaner** [comment]
Might seem odd, but I'm using GnuRoot to run linux on my android device and have had success using localtunnel to expose a web server. But it doesn't take long ( < 15 minutes) before the server closes with `connection refused: localtunnel.me:43027 (check your filewall settings)`. I'm connected to wifi for what it's worth, though it'd be cool if it was also possible over 4G

**Comment by WaKeMaTTa** [comment]
This issues is not fixed yet.

```
your url is: https://customname.localtunnel.me
/usr/lib/node_modules/localtunnel/bin/client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:44406 (check your firewall settings)
    at Socket.<anonymous> (/usr/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by defunctzombie** [comment]
Ill re-iterate here what I said in another issue on the client side. I don't have much time to work on localtunnel right now. I know these issues are happening and if someone wants to take master and fix it up I will happily review and deploy new versions but I want to be clear that I am not actively working on this day to day due to other obligations right now.

**Comment by tezlopchan** [comment]
create as bash script like try.sh with 
```
#!/bin/bash
lt --subdomain testratesyapp --port 3000
```
and then run ```watch n30 ./try.sh``` so this runs the try.sh every 30 sec 
and it worked for me with a constant subdomain..
i found no other solution.. works in ubuntu and all other linux OS i guess :)

**Comment by chodorowicz** [comment]
Also you could use pm2 or forever so it restart process when it fails.

**Comment by fantazer** [comment]
turnoff antivirus, this help me w10

**Comment by Laksa19** [comment]
create file localtunnel.desktop 

[Desktop Entry]
Version=1.0
Type=Application
Name=localtunnel
Comment=localtunnel tunneling localhost
Exec=watch -n 3 lt -s myweb -p 8080 && clear
Icon=knetattach
Path=
Terminal=true
StartupNotify=false

works in GNU/Linux

**Comment by DimasSup** [comment]
as variant for static subdomain 
shell script
`#!/bin/bash
while true
do
lt -p 9292 -s hpbuildserver
sleep 5
done
`
