### ISSUE TITLE
fixed subdomain for local tunneling?

### ISSUE THREAD

**Issue by deepseapenguin** [defunctzombie/localtunnel-server#145]
Is it possible to have fixed subdomain instead of random subdomain name?

for example, I wish to have fixed subdomain name like:
tunnel.example.com

instead of random domain name like:
honest-falcon-3.example.com
rare-warthog-96.example.com

**Comment by ianwijma** [comment]
Not sure if this is what you mean, but there is a `--subdomain` argument on the client.

ref: https://github.com/localtunnel/localtunnel#arguments
