### ISSUE TITLE
Error no such file or directory

### ISSUE THREAD

**Issue by FreshImmuc** [defunctzombie/localtunnel-server#166]
Hi, I installed it via. npm and now I am getting this issue:

![image](https://user-images.githubusercontent.com/65733898/133309319-97d46f55-85b3-4f6a-b81d-dc698b367cab.png)

What can I do to fix this? I already googled and tried dos2unix but it did not work... (it worked but it wasn't the problem)

**Comment by TheBoroer** [comment]
Duplicate / Related to: https://github.com/localtunnel/server/issues/139#issuecomment-718039420

**Comment by FreshImmuc** [comment]
Yes. It worked. #90 #139

Thank you for this fast response and have a great day!
