### ISSUE TITLE
API Endpoint to get info about a tunnel

### ISSUE THREAD

**Issue by cinaryilmaz** [defunctzombie/localtunnel-server#178]
Something like `/api/tunnel/<subdomain>` would be nice to learn if the tunnel exists and what's the port if it exists.

**Comment by TheBoroer** [comment]
I believe that already exists [here](https://github.com/localtunnel/server/blob/master/server.js#L39)

Have a look at: `/api/tunnels/<subdomain>/status` when you're connected

**Comment by cinaryilmaz** [comment]
Oh, thanks! I thought it didn't exist because it wasn't documented in README.md.
