### ISSUE TITLE
404 and client crashes after a few seconds after connect to my own localtunnel server

### ISSUE THREAD

**Issue by im-srj** [defunctzombie/localtunnel-server#192]
hi, I am aware of a similar issues, however, those are outdated and no longer works for me. I have followed the instructions from this article []https://medium.com/quark-works/running-your-own-reverse-proxy-with-localtunnel-b1658e239c35 to set up a localtunnel server, but when I try to connect from a client machine, it shows a 404 error and automatically disconnects after a few seconds.

**Comment by im-srj** [comment]
thanks everyone, I figured it out.

**Comment by Amit-A** [comment]
@Im-SRJ I'm facing the same issue! How did you resolve it?
