### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by vvo** [defunctzombie/localtunnel-server#21]
Hi, here's what I did:

- setup *.localtunnel.function.fr CNAME function.fr.
- ping localtunnel.function.fr works
- ping dsadsa.localtunnel.function.fr works
- using `lt --host http://localtunnel.function.fr --port 8080` fails

It fails because maybe_bounce() does not find any client and so `return true;` and respond 502 to client.

I wonder how this could work, I know it does, but can you help on this? Everything is up and running if you want to test.

Also, I am setting this up because I get "Not running" errors most of the time while testing with zuul/saucelabs.

**Comment by vvo** [comment]
Would https://github.com/inconshreveable/ngrok be a more reliable solution to localtunneling with zuul? I really want my zuul testing flow to be reliable.

Either ngrok or sauceconnect would be good, maybe you know exactly what's wrong with the localtunnel issues..?

**Comment by vvo** [comment]
I removed the last comment, not relevant. I only really want to make localtunnel-server work.. Can you help @defunctzombie?

**Comment by defunctzombie** [comment]
How does `ping dsadsa.localtunnel.function.fr works` work if no tunnel has yet been established?

**Comment by vvo** [comment]
Because there's a wildcard DNS set on *.function.fr.

**Comment by vvo** [comment]
Maybe we can chat on gitte quickly to solve this.

**Comment by defunctzombie** [comment]
Sure. Link me.

**Comment by vvo** [comment]
Reading the code: https://github.com/defunctzombie/localtunnel-server/blob/master/server.js#L28

When doing a requets, it goes to maybe_bounce(), I have a hostname, I have a subdomain (localtunnel.function.fr is a subdomain), returns false.

**Comment by vvo** [comment]
AH! I know, is localtunnel compatible with being served on a subdomain? This is the case: I am trying to use --lt localtunnel.function.fr, it may break?

**Comment by defunctzombie** [comment]
I think as long as the server code around identifying the "client id" (subdomain) is correct it should work. That code (using the module to do that) might be wrong or returning too much of the subdomain.

**Comment by vvo** [comment]
https://gitter.im/defunctzombie/localtunnel-server But you have to create it.

**Comment by defunctzombie** [comment]
I suspect it is returning everything before `function.fr` instead of just the stuff before the first dot.

**Comment by vvo** [comment]
So the strategy is:

if no hostname return false (go to localtunnel app)
if no subdomain (clientID) then return false, but in my case, it's returning "localtunnel"

**Comment by vvo** [comment]
I will try to host localtunnel on a top level TLD, it should work then

**Comment by defunctzombie** [comment]
Yea. I think the code could be made to handle this better. It may be that auto-detecting the "base domain" part is not a great way to do it and we can just accept an ENV var for the basename.

**Comment by defunctzombie** [comment]
Yes, as a top level domain it should work.

**Comment by vvo** [comment]
So tried the toplevel, now it almost work:

```shell
> lt --host http://localtunnel.eu --port 8080
your url is: http://pgpnimhrzm.localtunnel.eu

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connection refused: localtunnel.eu:46831 (check your firewall settings)
    at Socket.<anonymous> (/home/vvo/.nvm/v0.10.36/lib/node_modules/localtunnel/client.js:84:32)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)

```

**Comment by vvo** [comment]
My server seems to not have any specific iptables rule set, strange

**Comment by defunctzombie** [comment]
Make sure your local network is also not doing anything funky. Sometimes
outbound connections on high ports are blocked to protect against malware.

**Comment by vvo** [comment]
Sometimes it just works and I get a url but then going to the url, it says "no active client.."

**Comment by vvo** [comment]
I should note, using localtunnel.me always works

**Comment by vvo** [comment]
http://localtunnel.eu/ app is showing, at least something works :D

**Comment by vvo** [comment]
rebooting, because, well..

**Comment by vvo** [comment]
now it works (sometimes), but all I can get is "localtunnel error: no active client for 'xxxxx'", omg

**Comment by vvo** [comment]
specifying a subdomain will always work,untill I shutdown/restart the server and try to reuse the same domain, then it fails with connection refused, what is different from my server from yours localtunnel.me. that's magic

**Comment by vvo** [comment]
mhh might be a DNS problem, seems like *.localtunnel.eu does not resolves to the good IP..

**Comment by vvo** [comment]
Ok now it works but I still have the sort of caching issue that when restarting the localtunnel server, it will fail from the client side with "connection refused".

Maybe DNS configuration/caching involved or some unclosed connection somewhere

**Comment by vvo** [comment]
Ok I think Ill use sauce connect for my needs, thanks for help
