### ISSUE TITLE
Docker friendly

### ISSUE THREAD

**Issue by wernight** [defunctzombie/localtunnel-server#22]
To be able to Dockerify the server a few things seem required to be fixed:

* Must not require connection of clients to a random port.
* Should outputs errors and logs to stdout/stderr.
* Should provide a README for the [localtunnel-server Docker](https://registry.hub.docker.com/u/defunctzombie/localtunnel-server/) showing how to use it
* Could change [localtunnel-server Docker](https://registry.hub.docker.com/u/defunctzombie/localtunnel-server/) to run as non-privileged user (set `USER`)
* `lt` client could be more descriptive when it fails (currently shows `Error: localtunnel server returned an error, please try again` with a stack trace and nothing more).

**Comment by wernight** [comment]
It may actually be more related to https://github.com/defunctzombie/localtunnel-server/issues/13

**Comment by defunctzombie** [comment]
Errors are already output when they happen.

**Comment by defunctzombie** [comment]
Connection of clients to a randomly assigned port is the entire way localtunnel works

**Comment by defunctzombie** [comment]
I could run it as non-root, but I really don't care that much :)

**Comment by defunctzombie** [comment]
FYI, I run the docker image on the primary localtunnel server so these are all likely "good to have" not "need to have"

**Comment by defunctzombie** [comment]
README updates for sure would help, but the gist of how I run the server is simply the two commands in run.sh

https://github.com/defunctzombie/localtunnel-server/tree/master/devops

**Comment by defunctzombie** [comment]
@wernight I think dockerhub makes the readme a copy of the github readme automatically.

Also, you just need to run with `--net host` to get this running under docker because of how localtunnel works.
